
[build]
  # El comando para construir tu sitio.
  command = "npm run build"
  # El directorio que Netlify debe publicar. Para el runtime de Next.js, es `.next`.
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
