

# El plugin de Next.js se encargar치 de todo autom치ticamente.
# Netlify lo detecta gracias a tu `package.json`, pero es buena pr치ctica
# especificarlo para asegurar que se use la versi칩n correcta.
[[plugins]]
  package = "@netlify/plugin-nextjs"
